<?php
/**
 * Ho_LayeredLanding
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the H&O Commercial License
 * that is bundled with this package in the file LICENSE_HO.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.h-o.nl/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@h-o.com so we can send you a copy immediately.
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright Â© 2014 H&O (http://www.h-o.nl/)
 * @license     H&O Commercial License (http://www.h-o.nl/license)
 * @author      Bram van der Horst <bram@h-o.nl>
 */
?>
<?php /** @var Hackathon_Layeredlanding_Block_Widget_List $this */ ?>
<?php if ($this->getLandingpageCollection()->count()): ?>
<div class="panel panel-clean panel-landingpage-list">
    <?php if($this->getTitle()):?>
    <div class="panel-heading">
        <strong><span><?php echo $this->getTitle();?></span></strong>
    </div>
    <?php endif;?>

    <ul>
        <?php foreach($this->getLandingpageCollection() as $landingpage): ?>
        <?php /** @var Hackathon_Layeredlanding_Model_Layeredlanding $landingpage */ ?>
        <li>
            <a href="<?php echo $landingpage->getUrl() ?>"><?php echo $landingpage->getPageTitle() ?></a>
        </li>
        <?php endforeach;?>
    </ul>
</div>
<?php endif; ?>
